project:
  type: website

website:
  title: "Henry Wu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: research.qmd
      - href: notes.qmd
      
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true


