---
title: "About Me"
---

I am a PhD student in Buddhist studies at the International College for Postgraduate Buddhist Studies (ICPBS) in Tokyo, Japan. I am a philologist (a person who studies old texts and the languages they’re written in) who specialises in Chinese translations of Buddhist scriptures made in the early medieval period (c. 200-600 AD) and their commentaries. 

I work with Sanskrit, Prakrit, Chinese and Tibetan sources to trace the history of how Buddhist texts were translated and transmitted from India to China, via Central Asia. My thesis research focuses on Kumārajīva, a Central Asian monk from Kucha (present-day Xinjiang, western China) and the translations he made in China with a team of Chinese monks at the beginning of the fifth century CE. My thesis investigates in new detail how he and his team produced their translations and the choices of language they made. 

A second and related research interest of mine is Chinese Buddhist commentarial literature, i.e. texts that Chinese monks composed in order to explain the meaning of translated scripture. I am particularly interested in how commentaries implicitly and explicitly grapple with the concept of translation, and how the line between exegesis and translation is always blurred. 

The broader themes that anchor my research are cross-cultural and cross-linguistic interaction, and how study of these exchanges in premodern Asia illuminate similarities and differences with our globally interconnected world today. 

Born and raised in Sydney, Australia, I completed my Bachelor of Philosophy (Honours) degree at the Australian National University in Canberra majoring in Linguistics, and then my MA in Buddhist Studies at ICPBS. 