---
title: Research
---

<h2>Peer-reviewed publications</h2>

- 2026.03. 'A Re-examination of the ‘Western Text’ 胡本 Quoted in the <em>Zhu Weimojie jing</em> 注維摩詰經'. <em>Journal of Indian and Buddhist Studies</em> 『印度學佛教學研究』 74.3: 1226-1229. (Erratum: The subheading '2. The name of the text' should read '2. The nature of the text'.) <br>
- 2025.12. ['Patterns of Textual Variation between Kumārajīva’s Chinese Translation of the <em>Vimalakīrtinirdeśa</em> and the Sanskrit Text and Other Translations.'](https://icabs.repo.nii.ac.jp/records/2000235) <em>Sengokuyama Journal of Buddhist Studies</em> 『仙石山仏教学論集』 16: 65-115.

<h2>Conference presentations and talks</h2>
- 2026.01.28. 'Towards a Reconstruction of Sengrui’s Lost Commentary on the
<em>Vimalakīrtinirdeśa</em>
僧叡『毘摩羅詰堤經義疏』の復元へ'. International College for Postgraduate Buddhist Studies (ICPBS). <br>
- 2025.09.06. 'A Re-examination of the ‘Western Text’ 胡本 Quoted in the <em>Zhu Weimojie jing</em> 注維摩詰經.' 76th Conference of the Japanese Association of Indian and Buddhist Studies, University of Osaka. <br>
- 2024.07.10. 'A Comparative Study of the Language of Kumārajīva’s Translation of the <em>Vimalakīrtinirdeśa</em>'. ICPBS.<br>
- 2020.08.06. 'Buddhist Translations as Language Contact'. Tianzhu International and Intensive Program on Buddhism at McMaster University, online.<br>